# Generated by Django 2.2.5 on 2019-10-01 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heartapi', '0005_auto_20190929_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='exang',
        ),
        migrations.AddField(
            model_name='test',
            name='angina',
            field=models.CharField(choices=[('0', 'No'), ('1', 'Yes')], default=0, max_length=30),
        ),
    ]
